#!/usr/bin/env bash
# Sourced after fetching AV. Preserve existing OMA trees; prepareOma owns updates.

MANAGED_DIR_POLICIES=(.agents:seed .claude:seed .codex:seed .cursor:seed .qwen:seed .grok:seed .gemini:seed .kimi-code:link .kimi:link .opencode:link)

is_managed_dir() {
  local policy
  for policy in "${MANAGED_DIR_POLICIES[@]}"; do
    if [[ "$1" == "${policy%:*}" ]]; then return 0; fi
  done
  return 1
}

harness_conflict() {
  err "Harness conflict at ${TARGET_DIR}/$1. Existing files were retained. Keep the custom file and resolve the conflict, or install into another target; --yes does not authorize replacement."
  exit 1
}

check_target_path() {
  local rel="$1" path="${TARGET_DIR}/$1"
  while [[ "$path" != "$TARGET_DIR" ]]; do
    [[ ! -L "$path" ]] || harness_conflict "$rel"
    if [[ "$path" != "${TARGET_DIR}/$rel" && -e "$path" && ! -d "$path" ]]; then
      harness_conflict "$rel"
    fi
    path="$(dirname "$path")"
  done
}

preflight_file() {
  local rel="$1" allow_existing="${2:-false}" src="${SOURCE_DIR}/$1" dst="${TARGET_DIR}/$1"
  [[ -e "$src" || -L "$src" ]] || return 0
  [[ -f "$src" && ! -L "$src" ]] || harness_conflict "$rel"
  check_target_path "$rel"
  if [[ -e "$dst" ]]; then
    [[ -f "$dst" ]] || harness_conflict "$rel"
    if [[ "$allow_existing" != true ]] && ! cmp -s "$src" "$dst"; then harness_conflict "$rel"; fi
  fi
}

preflight_dir() {
  local rel="$1" src="${SOURCE_DIR}/$1" dst="${TARGET_DIR}/$1" entry child resolved root
  [[ -d "$src" ]] || return 0
  [[ ! -L "$src" ]] || harness_conflict "$rel"
  if is_managed_dir "$rel" && [[ -L "$dst" ]]; then
    # Retain an existing internal managed link without copying into its target.
    resolved="$(cd "$dst" 2>/dev/null && pwd -P)" || harness_conflict "$rel"
    root="$(cd "$TARGET_DIR" && pwd -P)"
    [[ "$resolved" == "$root/"* ]] || harness_conflict "$rel"
    return 0
  fi
  check_target_path "$rel"
  [[ ! -e "$dst" || -d "$dst" ]] || harness_conflict "$rel"
  if is_managed_dir "$rel"; then return 0; fi
  while IFS= read -r -d '' entry; do
    child="${entry#"${SOURCE_DIR}/"}"
    check_target_path "$child"
    if [[ -d "$entry" && ! -L "$entry" ]]; then
      [[ ! -e "${TARGET_DIR}/$child" || -d "${TARGET_DIR}/$child" ]] || harness_conflict "$child"
    else
      preflight_file "$child"
    fi
  done < <(find "$src" -mindepth 1 -print0)
}

preflight_harness() {
  local rel policy
  for policy in "${MANAGED_DIR_POLICIES[@]}"; do preflight_dir "${policy%:*}"; done
  preflight_dir docs
  for rel in scripts/harness/gc.sh scripts/harness/validate.sh av.example.yaml; do preflight_file "$rel"; done
  if [[ "$MODE" == existing ]]; then
    for rel in AGENTS.md CLAUDE.md .gitignore; do preflight_file "$rel" true; done
  else
    for rel in AGENTS.md CLAUDE.md .gitignore scripts/dev.sh; do preflight_file "$rel"; done
    preflight_dir src
  fi
  if [[ "$INSTALL_WORKFLOWS" == true ]]; then preflight_dir .github; fi
}

copy_managed_dirs() {
  local policy
  for policy in "${MANAGED_DIR_POLICIES[@]}"; do
    # Runtime-derived trees are generated by OMA, never seeded from AV's repo.
    if [[ "${policy#*:}" == seed ]]; then copy_dir "${policy%:*}"; fi
  done
}

copy_dir() {
  local rel="$1" src="${SOURCE_DIR}/$1" dst="${TARGET_DIR}/$1"
  [[ -d "$src" ]] || return 0
  if is_managed_dir "$rel" && [[ -d "$dst" ]]; then
    info "Preserved ${rel}/; av setup prepares OMA through its supported installer."
    return 0
  fi
  mkdir -p "$dst"
  cp -Rn "${src}/." "$dst/"
  success "Copied  ${rel}/ (existing files retained)"
}

copy_file() {
  local rel="$1" src="${SOURCE_DIR}/$1" dst="${TARGET_DIR}/$1"
  [[ -f "$src" ]] || return 0
  if [[ -f "$dst" ]]; then info "Skipped ${rel} (already present)"; return 0; fi
  mkdir -p "$(dirname "$dst")"
  cp -n "$src" "$dst"
  success "Copied  ${rel}"
}
